# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d910049778899b22c20890e07bca7f575ba65e2cf3b0c45d62a0da1ec5571b65e5d915da51bbc8c5973c1dc023787b032348319d00f5edc82e39652f55b666fb

test:
  secret_key_base: d6829cdeaca5cdedcb947a4b33b08d1b9a7dec96f689acbc24fc8d61e52f40676054b06201aad6840a2b28c2d12096e53bea99c101cc483f980d76394e772899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
